### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [braze-inc/braze-gtm-actions#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The readme.md doesn't provide any information. Instead it redirects user to the gallery page which is irrelevant. Please provide valid information if any about the template.

**Comment by davidbielik** [comment]
Hi @praveena-pappu thanks for the prompt review! I've updated the repo with your requested changes.
