### ISSUE TITLE
Having issues with logging numbers/dates

### ISSUE THREAD

**Issue by Bengee07** [braze-inc/braze-gtm-actions#12]
GTM Web 4.8

Hello! I'm having some issues with logging of numbers/dates and would like your assistance.

This is GTM assistant's payload:

DOB:
![Screenshot 2024-01-10 at 10 54 43 AM](https://github.com/braze-inc/braze-gtm-actions/assets/152957643/41c2719a-9697-4efb-9e7a-5716921c59be)

Purchase:
![Screenshot 2024-01-10 at 10 54 38 AM](https://github.com/braze-inc/braze-gtm-actions/assets/152957643/57d6c649-4c7a-4526-ac86-b56a97f6c1d5)

This is what I'm getting in console logs:

DOB:
![Screenshot 2024-01-10 at 10 57 52 AM](https://github.com/braze-inc/braze-gtm-actions/assets/152957643/504bf80b-0acf-4bef-a015-800107ad3e35)

Relevant code:
DOB:
<img width="620" alt="Screenshot 2024-01-10 at 10 39 27 AM" src="https://github.com/braze-inc/braze-gtm-actions/assets/152957643/b56a76e2-9e43-4863-82c1-ccda88be18ad">

Purchase:
<img width="636" alt="Screenshot 2024-01-10 at 10 42 30 AM" src="https://github.com/braze-inc/braze-gtm-actions/assets/152957643/51135971-ed58-4be6-8dcc-90ae825cf53f">

In my form, DOB is specified as date and Purchase Quantity and Price is specified as number. From what I can see the payload GTM is sending to Braze is correct but seems to get rejected. How do I fix this?

**Comment by davidbielik** [comment]
Hi @Bengee07 can you also provide a screenshot of the GTM tag you're using to set the DOB in Braze, and the purchase price?

**Comment by Bengee07** [comment]
Hi @davidbielik, please find screenshot below.

<img width="424" alt="Screenshot 2024-01-10 at 10 34 26 PM" src="https://github.com/braze-inc/braze-gtm-actions/assets/152957643/d42d8804-a2fd-446a-a325-f24e05106447">

<img width="893" alt="Screenshot 2024-01-10 at 10 35 56 PM" src="https://github.com/braze-inc/braze-gtm-actions/assets/152957643/74ea9cc7-418a-460a-9038-0d1a37da4d09">

<img width="907" alt="Screenshot 2024-01-10 at 10 40 03 PM" src="https://github.com/braze-inc/braze-gtm-actions/assets/152957643/95406ffe-188a-45d6-bbdd-6ee53b82f89d">

**Comment by davidbielik** [comment]
@Bengee07 

1. For the purchase, you're forgetting to wrap those variables as `{{ variable }}` so it's passing the literal string of "brazePrice"

2. For the DOB, that's also being passed as a string, `"1776, 7, 4"`. Instead you'll need to either: (A) pass 3 separate properties (year, month, day), or (B) write javascript to split that value by `,`. For example (though please test it beforehand):

```
<script>
(function(){
   var parts = {{dob}}.split(", ");
   window.braze.getUser().setDateOfBirth(parts[0], parts[1], parts[3]);
})();
</script>
```

**Comment by Bengee07** [comment]
Hey @davidbielik , thank you for your help! I've made the changes and it works now. For the DOB I  used A and logged 3 separate properties as I wasn't able to get the javascript to work. Cheers!
