### ISSUE TITLE
Add/update custom user attributes 

### ISSUE THREAD

**Issue by mariusrudolph** [braze-inc/braze-gtm-actions#4]
Hi there,
We would like to add or update one or more customer attributes when firing a braze action tag. At the moment this it not possible because it is only allows to add event properties via the GTM template. 

For example:

We have a custom user attribute called “last_used_product” (ex. app_ios, app_android, web, etc). This custom user attribute should be updated/added when a user triggers the add_to_cart event so our CRM team can use this information to better personalize their campaigns. 

We cannot use it as an event property because those information are only stored for 30 days in braze.

**Comment by davidbielik** [comment]
Hi @mariusrudolph, unfortunately the way GTM tag templates work, it's not possible to call the `getUser().setCustomUserAttribute()` method from our SDK.

As a workaround, please follow the guide to setting custom attributes that's outlined in our [Documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/web/google_tag_manager/#custom-attributes).
