### ISSUE TITLE
disableSdk should be disableSDK (same for enable)

### ISSUE THREAD

**Issue by Minishlink** [braze-inc/braze-gtm-actions#8]

**Comment by davidbielik** [comment]
Hi @Minishlink thanks for reporting this. We'll review and release a fix for this.

**Comment by Minishlink** [comment]
Thanks @davidbielik

**Comment by davidbielik** [comment]
Hi @Minishlink thanks again for reporting this. We just released a fix, which should be available as soon as GTM picks it up on their end.

https://www.braze.com/docs/developer_guide/platform_integration_guides/web/google_tag_manager/#upgrading
